name: amazon-review-inference-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas
      - scikit-learn
      - joblib
      - numpy
      - azureml-core
      - azureml-inference-server-http